version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "java-lambda-snapstart"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pmwwgbzgw6qt"
s3_prefix = "java-lambda-snapstart"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
